version: '3.8'

services:
  # Bot service configured for MongoDB
  botwa:
    build: .
    container_name: botwa
    restart: unless-stopped
    environment:
      - TZ=Asia/Jakarta
      - NODE_ENV=production
      - DATABASE_TYPE=mongodb
    volumes:
      - ./auth:/app/auth
      - ./memory:/app/memory
      - ./config.js:/app/config.js
    networks:
      - botwa-network
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('healthy')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # MongoDB database
  mongodb:
    image: mongo:6.0
    container_name: botwa-mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=botwa_admin
      - MONGO_INITDB_ROOT_PASSWORD=change_this_password
      - MONGO_INITDB_DATABASE=botwa
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"
    networks:
      - botwa-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 40s

  # MongoDB Express - Web UI for database management
  mongo-express:
    image: mongo-express:1.0.0
    container_name: botwa-mongo-express
    restart: unless-stopped
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=botwa_admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=change_this_password
      - ME_CONFIG_MONGODB_URL=mongodb://botwa_admin:change_this_password@mongodb:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
      - ME_CONFIG_SITE_BASEURL=/mongo
    ports:
      - "8081:8081"
    networks:
      - botwa-network
    depends_on:
      mongodb:
        condition: service_healthy

networks:
  botwa-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
